#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# Bose-SoundTouch soundtouch-service installer for Keenetic routers (Entware)
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/gesellix/Bose-SoundTouch/main/scripts/keenetic/install.sh | bash
#
# Or download and run locally:
#   sudo bash install.sh
#
# Environment variables (override defaults via env):
#   VERSION=v0.93.1
#   DATA_DIR=/tmp/data
# ==============================================================================

VERSION="${VERSION:-v0.93.1}"
BINARY_NAME="${BINARY_NAME:-soundtouch-service}"
DATA_DIR=/tmp/data

if [[ ! "$VERSION" =~ ^v ]]; then
  VERSION="v${VERSION}"
fi

log() { printf "\n==> %s\n" "$*"; }
warn() { printf "\n⚠️  %s\n" "$*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

need_ssh() {
  if ! ssh -o BatchMode=yes -o ConnectTimeout=5 root@"${ROUTER_IP}" exit 2>/dev/null; then
    die "Cannot connect to router at ${ROUTER_IP}. Check IP and SSH access."
  fi
}

detect_arch() {
  local arch
  arch="$(ssh root@"${ROUTER_IP}" uname -m)"
  case "$arch" in
    aarch64) echo "keenetic-arm64" ;;
    armv7l)  echo "keenetic-arm" ;;
    mips)    echo "keenetic-mips" ;;
    mipsle)  echo "keenetic-mipsle" ;;
    *)
      die "Unsupported architecture: $arch (uname -m on router)"
      ;;
  esac
}

get_binary_url() {
  local arch="$1"
  echo "https://github.com/gesellix/Bose-SoundTouch/releases/download/${VERSION}/${BINARY_NAME}-${arch}"
}

check_dependencies() {
  log "Checking router dependencies..."
  ssh root@"${ROUTER_IP}" "
    if ! command -v curl >/dev/null 2>&1 && ! command -v wget >/dev/null 2>&1; then
      opkg update && opkg install curl
    fi
  "
}

ensure_data_dir() {
  log "Creating data directory..."
  ssh root@"${ROUTER_IP}" "mkdir -p ${DATA_DIR}"
}

download_binary() {
  local arch="$1"
  local url
  arch="${ARCH:-$(detect_arch)}"
  url="$(get_binary_url "$arch")"

  log "Downloading ${BINARY_NAME}-${arch} (version ${VERSION})..."
  log "URL: ${url}"

  ssh root@"${ROUTER_IP}" "
    cd /tmp
    if command -v curl >/dev/null 2>&1; then
      curl -fsSL -o ${BINARY_NAME} '${url}'
    else
      wget -qO ${BINARY_NAME} '${url}'
    fi
    chmod +x ${BINARY_NAME}
  "

  log "Binary installed to /tmp/${BINARY_NAME}"
}

write_init_script() {
  local arch="$1"
  log "Creating init script..."

  ssh root@"${ROUTER_IP}" "cat > /opt/etc/init.d/S99soundtouch" <<'EOFSCRIPT'
#!/bin/sh
# Auto-generated by soundtouch-service installer
# https://github.com/gesellix/Bose-SoundTouch

NAME=soundtouch-service
DAEMON=/tmp/soundtouch-service
DATA_DIR=${DATA_DIR:-/tmp/data}
PIDFILE=/var/run/${NAME}.pid

start() {
    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
        echo "$NAME is already running"
        return 1
    fi
    echo "Starting $NAME..."
    cd /tmp
    $DAEMON &
    echo $! > $PIDFILE
}

stop() {
    if [ ! -f "$PIDFILE" ]; then
        echo "$NAME is not running"
        return 1
    fi
    echo "Stopping $NAME..."
    kill $(cat "$PIDFILE") 2>/dev/null || killall $NAME 2>/dev/null
    rm -f $PIDFILE
}

status() {
    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
        echo "$NAME is running (PID: $(cat $PIDFILE))"
    else
        echo "$NAME is not running"
    fi
}

case "$1" in
    start)   start ;;
    stop)    stop ;;
    restart) stop; sleep 1; start ;;
    status)  status ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
EOFSCRIPT

  ssh root@"${ROUTER_IP}" "chmod +x /opt/etc/init.d/S99soundtouch"
}

write_autostart() {
  log "Configuring auto-start..."
  ssh root@"${ROUTER_IP}" "
    if ! grep -q 'S99soundtouch' /opt/etc/rc.local 2>/dev/null; then
      echo '/opt/etc/init.d/S99soundtouch start' >> /opt/etc/rc.local
    fi
    chmod +x /opt/etc/rc.local
  "
}

start_service() {
  log "Starting service..."
  ssh root@"${ROUTER_IP}" "/opt/etc/init.d/S99soundtouch start"
  sleep 2
}

health_check() {
  local port="${PORT:-8080}"
  local max_retries=5
  local count=0

  log "Checking service health..."

  while [[ $count -lt $max_retries ]]; do
    if ssh root@"${ROUTER_IP}" "curl -sf http://localhost:${port}/health" >/dev/null 2>&1; then
      log "✅ Service is healthy and responding on port ${port}!"
      return 0
    fi
    echo "Waiting for service... ($((count+1))/$max_retries)"
    sleep 2
    count=$((count+1))
  done

  warn "Service started but did not respond to health check."
  warn "Check logs with: ssh root@${ROUTER_IP} /tmp/${BINARY_NAME} -v"
  return 1
}

show_status() {
  ssh root@"${ROUTER_IP}" "/opt/etc/init.d/S99soundtouch status"

  cat <<EOF

Access the service at:
  http://${ROUTER_IP}:8080

Manage the service:
  ssh root@${ROUTER_IP} /opt/etc/init.d/S99soundtouch {start|stop|restart|status}

View logs (run in foreground):
  ssh root@${ROUTER_IP} /tmp/${BINARY_NAME} -v
EOF
}

usage() {
  cat <<EOF
Usage: ROUTER_IP=192.168.1.1 [OPTIONS] bash install.sh

Environment variables:
  ROUTER_IP      Router IP address (required)
  VERSION        Release version to install (default: v0.93.1)
  ARCH           Override architecture detection (e.g., keenetic-arm64)
  DATA_DIR       Data directory (default: /tmp/data)
  PORT           Service port (default: 8080)

Examples:
  # Install latest release
  ROUTER_IP=192.168.1.1 bash install.sh

  # Install specific version
  ROUTER_IP=192.168.1.1 VERSION=v0.94.0 bash install.sh

  # Override architecture
  ROUTER_IP=192.168.1.1 ARCH=keenetic-arm64 bash install.sh
EOF
}

main() {
  if [[ -z "${ROUTER_IP:-}" ]]; then
    if [[ "${1:-}" == "-h" ]] || [[ "${1:-}" == "--help" ]]; then
      usage
      exit 0
    fi
    echo "ERROR: ROUTER_IP is required"
    echo
    usage
    exit 1
  fi

  log "Installing ${BINARY_NAME} ${VERSION} on Keenetic router at ${ROUTER_IP}"

  need_ssh
  check_dependencies
  ensure_data_dir
  download_binary
  write_init_script
  write_autostart
  start_service
  health_check
  show_status

  log "Installation complete!"
}

main "$@"
